"""
Database Models
===============
All SQLAlchemy models for the monitoring system.

Tables:
  users        — authorized system users
  login_logs   — every login / logout attempt (success & failure)
  devices      — network hardware being monitored
  access_logs  — actions performed against devices
  alerts       — security alerts generated by the system
"""

from extensions import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime


# ── User loader required by Flask-Login ─────────────────────────────────────
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


# ────────────────────────────────────────────────────────────────────────────
class User(UserMixin, db.Model):
    """
    Authorized system users.
    Roles: 'admin' (full access) | 'viewer' (read-only dashboard)
    """
    __tablename__ = 'users'

    id           = db.Column(db.Integer, primary_key=True)
    username     = db.Column(db.String(80),  unique=True, nullable=False, index=True)
    password_hash= db.Column(db.String(256), nullable=False)
    role         = db.Column(db.String(20),  default='viewer')   # 'admin' | 'viewer'
    created_at   = db.Column(db.DateTime,    default=datetime.utcnow)
    last_login   = db.Column(db.DateTime,    nullable=True)
    is_active    = db.Column(db.Boolean,     default=True)

    login_logs   = db.relationship('LoginLog', backref='user', lazy='dynamic')

    def set_password(self, password: str):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password: str) -> bool:
        return check_password_hash(self.password_hash, password)

    def is_admin(self) -> bool:
        return self.role == 'admin'

    def __repr__(self):
        return f'<User {self.username} [{self.role}]>'


# ────────────────────────────────────────────────────────────────────────────
class LoginLog(db.Model):
    """
    Immutable record of every login / logout attempt.
    Even failed attempts are recorded — this is the core evidence trail.
    """
    __tablename__ = 'login_logs'

    id                 = db.Column(db.Integer, primary_key=True)
    user_id            = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)
    username_attempted = db.Column(db.String(80))
    ip_address         = db.Column(db.String(45))   # IPv4 or IPv6
    user_agent         = db.Column(db.String(512))
    timestamp          = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    success            = db.Column(db.Boolean, default=False)
    action             = db.Column(db.String(20), default='login')  # 'login' | 'logout'

    def __repr__(self):
        status = 'OK' if self.success else 'FAIL'
        return f'<LoginLog {self.username_attempted} {status} @ {self.ip_address}>'


# ────────────────────────────────────────────────────────────────────────────
class Device(db.Model):
    """
    A monitored network hardware device.
    device_type: 'camera' | 'router' | 'switch'
    """
    __tablename__ = 'devices'

    id          = db.Column(db.Integer, primary_key=True)
    name        = db.Column(db.String(100), nullable=False)
    device_type = db.Column(db.String(50))
    ip_address  = db.Column(db.String(45))
    stream_url  = db.Column(db.String(512), nullable=True)   # MJPEG / snapshot URL for cameras
    status      = db.Column(db.String(20),  default='unknown')  # 'online'|'offline'|'unknown'
    last_seen   = db.Column(db.DateTime,    nullable=True)
    last_checked= db.Column(db.DateTime,    nullable=True)
    added_by    = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)

    access_logs = db.relationship('AccessLog', backref='device', lazy='dynamic')

    def status_badge(self) -> str:
        """Returns a Bootstrap badge class string."""
        return {'online': 'success', 'offline': 'danger', 'unknown': 'secondary'}.get(self.status, 'secondary')

    def __repr__(self):
        return f'<Device {self.name} [{self.ip_address}] {self.status}>'


# ────────────────────────────────────────────────────────────────────────────
class AccessLog(db.Model):
    """
    Records every access event to a device — both legitimate and unauthorized.
    """
    __tablename__ = 'access_logs'

    id           = db.Column(db.Integer, primary_key=True)
    device_id    = db.Column(db.Integer, db.ForeignKey('devices.id'), nullable=True)
    device_name  = db.Column(db.String(100))
    ip_address   = db.Column(db.String(45))
    action       = db.Column(db.String(100))   # 'ping_check', 'stream_access', 'config_change' …
    timestamp    = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    initiated_by = db.Column(db.String(80))    # username or 'system'
    result       = db.Column(db.String(20))    # 'success' | 'failed' | 'blocked'

    def __repr__(self):
        return f'<AccessLog {self.device_name} {self.action} {self.result}>'


# ────────────────────────────────────────────────────────────────────────────
class Alert(db.Model):
    """
    Security alerts generated by the system.
    severity: 'low' | 'medium' | 'high' | 'critical'
    """
    __tablename__ = 'alerts'

    id         = db.Column(db.Integer, primary_key=True)
    alert_type = db.Column(db.String(60))    # 'brute_force'|'device_offline'|'unauthorized_access'
    message    = db.Column(db.String(512))
    ip_address = db.Column(db.String(45),  nullable=True)
    timestamp  = db.Column(db.DateTime,    default=datetime.utcnow, index=True)
    resolved   = db.Column(db.Boolean,     default=False)
    severity   = db.Column(db.String(20),  default='medium')

    def severity_badge(self) -> str:
        return {'low': 'info', 'medium': 'warning', 'high': 'danger', 'critical': 'danger'}.get(self.severity, 'secondary')

    def __repr__(self):
        return f'<Alert [{self.severity}] {self.alert_type}: {self.message[:40]}>'
